<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>
		<AssemblyName>RootsBeta</AssemblyName>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RootsCore\RootsCore.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Daybreak">
	    <HintPath>lib\Daybreak.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>