<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>
		<AssemblyName>RootsBeta</AssemblyName>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>14.0</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\RootsCore\RootsCore.csproj" />
	</ItemGroup>

</Project>